[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
wasmtime = { version = "19.0", features = ["component-model"] }
wasmtime-wasi = "19.0"
anyhow = "1.0"
tokio = { version = "1.36", features = ["full"] }
notify = "6.1"
tao = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"