# examples/hello-window/Cargo.toml
[package]
name = "hello-window"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.36"
bytemuck = "1"

[profile.release]
opt-level = "s"
lto = true